{% set name = "zziplib" %}
{% set version = "0.13.76" %}
{% set sha256 = "08b0e300126329c928a41b6d68e397379fad02469e34a0855d361929968ea4c0" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/gdraheim/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - python
    - ninja
  host:
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libzzip${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/zzip.h  # [unix]
    - if NOT exist %LIBRARY_LIB%/zziplib.lib exit 1  # [win]
    - if NOT exist %LIBRARY_BIN%/zziplib.dll exit 1  # [win]
    - if NOT exist %LIBRARY_INC%/zzip/zzip.h exit 1  # [win]


about:
  home: http://zziplib.sourceforge.net/
  summary: The zziplib library is intentionally lightweight, it offers the ability to easily extract data from files archived in a single zip file.
  # See https://github.com/gdraheim/zziplib/blob/v0.13.69/README#L13-L18
  license: LGPL-2.0-or-later OR MPL-1.1
  license_file:
    - docs/COPYING.LIB
    - docs/COPYING.MPL
    - docs/copying.htm

extra:
  recipe-maintainers:
    - wolfv
    - traversaro
