{% set name = 'zziplib' %}
{% set version = '0.13.73' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/gdraheim/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2aa9d317f70060101064863e4e8fe698c32301e2d293d2b4964608cf2d5b2d8b


build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - cmake
    - ninja
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libzzip${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/zzip.h  # [unix]
    - if NOT exist %LIBRARY_LIB%/zziplib.lib exit 1  # [win]
    - if NOT exist %LIBRARY_BIN%/zziplib.dll exit 1  # [win]
    - if NOT exist %LIBRARY_INC%/zzip/zzip.h exit 1  # [win]


about:
  home: http://zziplib.sourceforge.net/
  summary: The zziplib library is intentionally lightweight, it offers the ability to easily extract data from files archived in a single zip file.
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING.LIB

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
