{% set name = "zziplib" %}
{% set version = "0.13.72" %}
{% set sha256 = "93ef44bf1f1ea24fc66080426a469df82fa631d13ca3b2e4abaeab89538518dc" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/gdraheim/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      # python 2 only for docs building
      - remove_docs_from_build.patch
  - path: CMakeLists.txt  # [win]

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - pkg-config
    - autoconf  # [not win]
    - cmake  # [win]
    - python
    - make
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libzzip${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/zzip.h  # [unix]
    - if NOT exist %LIBRARY_LIB%/zziplib.lib exit 1  # [win]
    - if NOT exist %LIBRARY_BIN%/zziplib.dll exit 1  # [win]
    - if NOT exist %LIBRARY_INC%/zzip/zzip.h exit 1  # [win]


about:
  home: http://zziplib.sourceforge.net/
  summary: The zziplib library is intentionally lightweight, it offers the ability to easily extract data from files archived in a single zip file.
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING.LIB

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
