travis:
  secure:
    BINSTAR_TOKEN: OQ8yzKOS30d8qzeB6C4vs9dYYOvi2xlrN23Zl3i82JAQKiMaw5EjIU2g3xAVB0/WtlORhAyoJ70oCYxP8tqYw30uvEsgtgsJFRDMJ5Njg2Kc2+XXUgLRVLAeT3mCY32pJ338w6lUp2pGZl8KSECIBPAvE4SVw+5M1qbD/lOkpJz/h6wOcbzmpUvdin2yxM3FNPzDo6Z/NUg8I/tKLK+srOiJy2iDaAX9cLeg6cblymOpRyffTzKz10ucnd3aVTRB2lo9JtZj9iE9Yfzp9EdLcJBIbcLJV2nwr0gxMXO9m75qE/2PhMakclhBMvgSUpSG2tWivMebpU0s6naCQhWy0t30ImZeRtjNlFUZ9MCLr1Cx/9bAqDn7gB/4DBmdeAZG4R6W+Q8tFFv1MO33SlfDuyQf0fIbwISaQxjYnyidzu0mnekhHIUeBZOwmKT+Eu8gq3E527AKYB6vzL/tq32GLeqK/xcbS5sOGqlk9gJKne7fJ/r49uc50Al4BXXHU/Y3jvkBU1f/47FDjiw8jZgJcF/8ynQqPDsCpmb+taoXEIyxqD0RxdIZoRlI07E7EndyuNLz8OKS7URahzvPJNCfBLou0eihVquEt9yh8YRBrHDF4BysfJRkg6+GFeZxKNXfD9xWTGKROQM7DT4ZCuDO7Z0tH/oOiPpv69CpLWCekaI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
